TimeTableBusTrain/Models/BusTimeTable.cs
using System;
using Data.Transports;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeTableBusTrain.Models
{
    public class BusTimeTable
    {
        public List<String> Sities { set; get; }
        public List<Bus> Buses { set; get; }
    }
}

TimeTableBusTrain/Models/BusTimeTableModel.cs
using System;
using Data.Transports;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeTableBusTrain.Models
{
    public class BusTimeTableModel
    {
        public List<String> Sities { set; get; }
        public List<Bus> Buses { set; get; }
    }
}

TimeTableBusTrain/Models/TrainTimeTable.cs
using System;
using Data.Transports;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeTableBusTrain.Models
{
    public class TrainTimeTable
    {
        public List<String> Sities { set; get; }
        public List<Train> Trains { set; get; }
    }
}

TimeTableBusTrain/Models/TrainTimeTableModel.cs
using System;
using Data.Transports;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeTableBusTrain.Models
{
    public class TrainTimeTableModel
    {
        public IEnumerable<String> Sities { set; get; }
        public IEnumerable<Train> Trains { set; get; }

        public TrainTimeTableModel(){}

    }
}

TimeTableBusTrain/Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic;
using Logic.Factory;

namespace TimeTableBusTrain.Controllers
{
    public class ChartsController : Controller
    {
        //
        // GET: /Charts/

        public ActionResult Index()
        {
            var creator = new Creator(new BusFactory());
            var list = creator.GetTransportList();
            var model = new Dictionary<string, int>();    
            foreach (var item in list)
            {
                int value;
                if (model.TryGetValue(item.CityTo, out value))
                {
                    model[item.CityTo] += item.DaysOfWeek.Count;
                }
                else
                {
                    model[item.CityTo] = item.DaysOfWeek.Count;
                }
            }
            return View(model);
        }

    }
}

TimeTableBusTrain/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TimeTableBusTrain.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

TimeTableBusTrain/Controllers/TimeTableController.cs
using System;
using System.Collections;
using System.Linq.Expressions;
using System.Reflection;
using System.Text;
using Data.Transports;
using Logic;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic.Factory;
using TimeTableBusTrain.Models;
using System.Collections.Generic;

namespace TimeTableBusTrain.Controllers
{
    public class TimeTableController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }
        
        public ActionResult Train()
        {

            //IFactory factory = new TrainFactory();
            //Creator creator = new Creator(factory);
            TrainTimeTableModel model = new TrainTimeTableModel
            {
                Trains = new List<Train>()
                {
                    new Train("qwe", 1),
                    new Train("asd", 2),
                    new Train("zxc", 3)
                }
            };
            
            return View(model);
        }

        [HttpGet]
        public ActionResult Bus()
        {
            IFactory factory = new BusFactory();
            var creator = new Creator(factory);

            var busList = new PageModel();
            busList.List.AddRange(creator.GetTransportList());
            if (Request.Params.Get("CityTo") != null && !Request.Params.Get("CityTo").Equals(""))
            {
                busList.List = busList.List.Where(x => ((Transport)x).CityTo.Equals(Request.Params.Get("CityTo"))).ToList();
            }
            if (Request.Params.Get("CityFrom") != null && !Request.Params.Get("CityFrom").Equals(""))
            {
                busList.List = busList.List.Where(x => ((Transport)x).CityFrom.Equals(Request.Params.Get("CityFrom"))).ToList();
            }
            if (Request.Params.Get("OnlyHolidays") != null && !Request.Params.Get("OnlyHolidays").Equals(""))
            {
                busList.List = busList.List.Where(x => ((Transport)x).DaysOfWeek.Contains("saturday") || ((Transport)x).DaysOfWeek.Contains("sunday")).ToList();
            }
            if (Request.Params.Get("selected[]") != null && !Request.Params.Get("selected[]").Equals(""))
            {
                var selected = Request.Params.Get("selected[]").Split(',');
                busList.List = busList.List.Where(x => selected.Contains(((Bus)x).NumberRoute.ToString())).ToList();
            }
            var clt = new CityList();
            clt.List.AddRange(creator.GetCitiesToList());
            var clf = new CityList();
            clf.List.AddRange(creator.GetCitiesFromList());

            var data = new ChartData();
            data.Prepare(busList.List.Select(x => (Transport) x).ToList());

            var model = new PageModel();
            model.Add(busList);
            model.Add(clt);
            model.Add(data);
            model.Add(clf);
            return View(model);
        }
    }
}

TimeTableBusTrain/Views/Charts/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>
<script>
    $(document).ready(function (){
        var data = [];
        var data2 = [];

        @foreach (var item in Model)
        {
            <text>
            data.push([
                "@item.Key",
                @item.Value
            ]);
        data2.push([
                "@item.Key",
                100 - @item.Value
        ]);
        </text>
        }

        $.jqplot('myChartCircleBus', [data],
        {
            seriesDefaults: {
                // Make this a pie chart.
                renderer: jQuery.jqplot.PieRenderer,
                rendererOptions: {
                    // Donut's can be cut into slices like pies.
                    sliceMargin: 3,
                    // Pies and donuts can start at any arbitrary angle.
                    startAngle: -90,
                    showDataLabels: true,
                    // By default, data labels show the percentage of the donut/pie.
                    // You can show the data 'value' or data 'label' instead.
                    dataLabels: 'percent'
                }
            },
            legend: { show: true, location: 'e' }
        });
        $.jqplot('myChartCircleTrain', [data2],
        {
            seriesDefaults: {
                // Make this a pie chart.
                renderer: jQuery.jqplot.PieRenderer,
                rendererOptions: {
                    // Donut's can be cut into slices like pies.
                    sliceMargin: 3,
                    // Pies and donuts can start at any arbitrary angle.
                    startAngle: -90,
                    showDataLabels: true,
                    // By default, data labels show the percentage of the donut/pie.
                    // You can show the data 'value' or data 'label' instead.
                    dataLabels: 'percent'
                }
            },
            legend: { show: true, location: 'e' }
        });

        $.jqplot('myChartLinear', [data], {
            title: 'Число маршрутов в город',
            series: [{ renderer: $.jqplot.BarRenderer }],
            axesDefaults: {
                tickRenderer: $.jqplot.CanvasAxisTickRenderer,
                tickOptions: {
                    angle: -30,
                    fontSize: '10pt'
                }
            },
            axes: {
                xaxis: {
                    renderer: $.jqplot.CategoryAxisRenderer
                }
            }
        });
    })
</script>
<div id="myChartCircleBus" style="width: 49%; display: inline-block"></div>
<div id="myChartCircleTrain" style="width: 49%; display: inline-block"></div>
<div id="myChartLinear"></div>

TimeTableBusTrain/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.jqplot.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.pieRenderer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.donutRenderer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.barRenderer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.canvasAxisTickRenderer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.categoryAxisRenderer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.dateAxisRenderer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqplot.canvasTextRenderer.min.js")" type="text/javascript"></script>
    <style>
        .jqplot-table-legend-swatch {
            width: 20px;
            height: 20px;
        }
    </style>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>Справочная система расписаний</h1>
            </div>
            <div id="logindisplay">
                <h4>***</h4>
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Главная", "Index", "TimeTable")</li>
                    <li>@Html.ActionLink("Автобусы", "Bus", "TimeTable")</li>
                    <li>@Html.ActionLink("Поезда", "Train", "TimeTable")</li>
                    <li>@Html.ActionLink("Графики", "Index", "Charts")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

TimeTableBusTrain/Views/TimeTable/Bus.cshtml
@{
    ViewBag.Title = "Bus";
}

<h2>Bus</h2>

<script>
    $(document).ready(function (){
        var data = [];

        @foreach (var item in Model.List[2].List)
        {
            <text>
            data.push([
                "@item.Key",
                @item.Value
            ]);
        </text>
        }

        $.jqplot('myChartCircleBus', [data],
        {
            seriesDefaults: {
                // Make this a pie chart.
                renderer: jQuery.jqplot.PieRenderer,
                rendererOptions: {
                    // Donut's can be cut into slices like pies.
                    sliceMargin: 3,
                    // Pies and donuts can start at any arbitrary angle.
                    startAngle: -90,
                    showDataLabels: true,
                    // By default, data labels show the percentage of the donut/pie.
                    // You can show the data 'value' or data 'label' instead.
                    dataLabels: 'percent'
                }
            },
            legend: { show: true, location: 'e' }
        });
    })
</script>


<form action="@Url.Action("Bus")">
    <div id="myChartCircleBus" style="width: 49%; display: inline-block"></div>
    <table style="width: 50%; display: inline-block;">
        <thead>
            <tr>
                <th colspan="2">
                    Фильтры:
                </th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td style="width: 50%">CityTo</td>
            <td style="width: 50%">
                <select name="CityTo">
                    <option value="">Не выбран</option>
                    @foreach (var city in Model.List[1].List)
                    {
                        <option value="@city" @if (Request.Params.Get("CityTo") != null && Request.Params.Get("CityTo").Equals(city)) 
                                              {<text>selected="selected"</text>}> @city</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>CityFrom</td>
            <td>
                <select name="CityFrom">
                    <option value="">Не выбран</option>
                    @foreach (var city in Model.List[3].List)
                    {
                        <option value="@city" @if (Request.Params.Get("CityFrom") != null && Request.Params.Get("CityFrom").Equals(city))
                                              {<text>selected="selected"</text>}> @city</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>OnlyHolidays</td>
            <td>
                <input type="checkbox" name="OnlyHolidays" value="checked" @if (Request.Params.Get("OnlyHolidays") != null && Request.Params.Get("OnlyHolidays").Equals("checked"))
                                                                           {<text>checked="checked"</text>}/>
            </td>
        </tr>
            </tbody>
    </table>
    <table id="with_filter">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    NumberRoute
                </th>
                <th>
                    BusModel
                </th>
                <th>
                    StartTime
                </th>
                <th>
                    FinishTime
                </th>
                <th>
                    DaysOfWeek
                </th>
                <th>
                    CityFrom
                </th>
                <th>
                    StationFrom(Platform)
                </th>
                <th>
                    CityTo
                </th>
                <th>
                    StationTo
                </th>
                <th>
                    Cost
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var bus in Model.List[0].List)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="selected[]" value="@bus.NumberRoute" />
                    </td>
                    <td>
                        @bus.NumberRoute
                    </td>
                    <td>
                        @bus.BusModel
                    </td>
                    <td>
                        @bus.StartTime
                    </td>
                    <td>
                        @bus.FinishTime
                    </td>
                    <td>
                        @foreach (var day in bus.DaysOfWeek)
                        {
                            <text>
                                @(day),
                            </text>
                        }
                    </td>
                    <td>
                        @bus.CityFrom
                    </td>
                    <td>
                        @bus.StationFrom
                        (@bus.Platform)
                    </td>
                    <td>
                        @bus.CityTo
                    </td>
                    <td>
                        @bus.StationTo
                    </td>
                    <td>
                        @bus.Cost
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <input type="submit" />
<button onclick="window.location.href='@Request.Path';return false;" style="font-size: 1.2em;padding: 5px;">Очистить</button>
</form>

TimeTableBusTrain/Views/TimeTable/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

TimeTableBusTrain/Views/TimeTable/Train.cshtml
@{
    ViewBag.Title = "Train";
}
<h2>Train</h2>

<table>
    <thead>
        <tr>
            <th>
                NumberTrain
            </th>
            <th>
                TypeTrain
            </th>
            <th>
                StartTime
            </th>
            <th>
                FinishTime
            </th>
            <th>
                CityFrom
            </th>
            <th>
                StationFrom(Platform)
            </th>
            <th>
                CityTo
            </th>
            <th>
                StationTo
            </th>
            <th>
                Cost
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var train in Model.Trains)
        {
            <tr>
                <td>
                    @train.NumberTrain
                </td>
                <td>
                    @train.TypeTrain
                </td>
                <td>
                    @train.StartTime
                </td>
                <td>
                    @train.FinishTime
                </td>
                <td>
                    @train.CityFrom
                </td>
                <td>
                    @train.StationFrom
                    (@train.Platform)
                </td>
                <td>
                    @train.CityTo
                </td>
                <td>
                    @train.StationTo
                </td>
                <td>
                    @train.Cost
                </td>
            </tr>
        }
    </tbody>
</table>